import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.scss";
import Header from "./ui/components/Header";
import { Footer } from "./ui/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`__variable_1e4310 __variable_c3aa02 ${geistSans.variable} ${geistMono.variable}`}
      >
        <header>
          <Header
            menu={[
              {
                title: "home",
                path: "/",
              },
              {
                title: "About",
                path: "/about",
              },
              {
                title: "Section",
                path: "/section",
              },
            ]}
            logo={{
              src: "/assets/7f.png",
              alt: "Image",
              width: 50,
              height: 50,
            }}
            dropDown={[
              {
                Links: [
                  { title: "Profile", path: "/profile" },
                  { title: "Settings", path: "/settings" },
                  { title: "Logout", path: "/logout" },
                ],
              },
            ]}
          />
        </header>
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
